- hosts: load-balancers
  
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ssh-key/vagrant
    environment: development # 'default' environment
  
  vars_files:
    - "environments/{{ environment }}.yml"

  roles:
    - { role: 'loadbalancer' }